#!/bin/bash

set -e

if [[ -n "${DEMO_APP_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Run api server tests.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        echo "Running api server tests..."
        docker compose up -d
        docker compose exec api yarn test
        docker compose down
    fi
fi